### ISSUE TITLE
MovieLens dataset is not loaded

### ISSUE THREAD

**Issue by JavaStudentAlex** [linafaik08/graph_neural_networks#1]
I use:
- pytorch-geometric==2.1.0

and got the error while running the 2nd cell in the [2_link_prediction.ipynb](https://github.com/linafaik08/graph_neural_networks/blob/98c7ea7ee29b8dbe4462a6a0894f4ea02add1620/2_link_prediction.ipynb) notebook:

```
dataset = MovieLens(root=folder, 'movielens')
                                                                      ^
SyntaxError: positional argument follows keyword argument
```
I have searched for the class annotation and found it:

```
class MovieLens(root, transform: Optional[Callable] = None, pre_transform: Optional[Callable] = None, model_name: Optional[str] = 'all-MiniLM-L6-v2')
```

The `root` param has to be in the first position without a key and the name of the model has to have the key.

**Comment by linafaik08** [comment]
Hello ! 

The code you are referring to is actually:
`dataset = MovieLens(root= os.path.join(folder.get_path(),'movielens'))`

If you want to rerun the code, you need to specify the path where you want to save the dataset in the argument `root`.

More info in the pytorch geom doc [here](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/datasets/movie_lens.html).

Hope it helps,
Lina

**Comment by JavaStudentAlex** [comment]
yep, than you for the comment, now I see what was the reason
